### PR TITLE
feat(lacework-agent): add `vmprovidercustom` value

### PR DESCRIPTION
**Pull request by nschmeller**
This commit adds the `vmprovidercustom` property to the `lacework-agent`
Helm charts.

Specifically, this commit:

* Adds an entry in the JSON schema for the `vmprovidercustom` key
* Adds templating to the configmap to render the `vmprovidercustom`
  config JSON if the Helm option is enabled
* Updates the `values.yaml` file to document this new Helm value

Resolves LINK-2104

### CODE REVIEW

**Review by rnalexlacework — APPROVED** [review]
Are we planning to push this to the agent repo as well. I have found that the helm tests covering these new options added are very useful for making sure that they work as intended.

**Comment by nschmeller** [comment]
> Are we planning to push this to the agent repo as well. I have found that the helm tests covering these new options added are very useful for making sure that they work as intended.

These changes were completed in the agent repo in d63e5a5c84959113dda3a82341b413f4259e9cb3 with tests

**Comment by nschmeller** [comment]
testing something

**Comment by rnalexlacework** [comment]
> > Are we planning to push this to the agent repo as well. I have found that the helm tests covering these new options added are very useful for making sure that they work as intended.
> 
> These changes were completed in the agent repo in d63e5a5c84959113dda3a82341b413f4259e9cb3 with tests

Nice. Thank you I missed that.

**Pull request merged**
