### PR TITLE
support providing access token with an existing secret

### LINKED ISSUE #18: Allow configuring access token with an existing secret.
When we configure new clusters we would like to be able to configure the access token with an existing secret instead of needing to hard code the token in a values file that we commit to a repository.

### PR DESCRIPTION
**Pull request by voldemortensen**
closes #18

### CODE REVIEW

**Comment by cirego** [comment]
Hey @voldemortensen, thanks for the contribution! I'm currently on PTO and will look at this early next week. Hope you have a great New Year!

**Comment by jhyelton** [comment]
Adding a ➕ to this request, this will be great for our use case as well.

**Comment by cirego** [comment]
Hi @jhyelton, thanks for the feedback!

To be transparent, I think this is a good change and I'm still working with Lacework legal to make sure we have the right process for accepting community contributions. Thanks, in advance, for your patience!

**Comment by cirego** [comment]
Hey @voldemortensen, we added the CLA Assistant to our repo as a requirement before we can merge this PR. This PR also needs to be updated, as there is a merge conflict. I can handle updating the PR and I will need your help by asking you to sign the CLA. Thanks!

**Comment by voldemortensen** [comment]
Thanks @cirego. I don't sign CLAs, personally. I'll see if I can make a company account and sign one on the companies behalf, not me personally.

In the meantime though, I release the changes I've made here into the public domain, so if anyone else willing to sign a CLA wants to open a pull request with them they are free to do so.

**Comment by cirego** [comment]
Hi @voldemortensen, I totally understand. Thanks for bringing this to my attention. I've filed an internal ticket to implement this functionality in the next release of our agent helm charts. Thanks again!

**Pull request closed without merging**
