### PR TITLE
Allow defininig necessary ENV vars

### PR DESCRIPTION
**Pull request by ajardan**
Adds functionality to adjust values for:
COOL_OFF_AFTER_TAG_COUNT
COOL_OFF_MILLISECONDS
MAX_CONCURRENT_SCANS

### CODE REVIEW

**Comment by ajardan** [comment]
Is there someone available to review and merge this ?

**Comment by cirego** [comment]
@michael-zhou-lw, are you able to take a look at this PR?

**Comment by michael-zhou-lw** [comment]
Thanks @cirego for tagging me!

@ajardan - Thanks for the PR! I will make this change internally so that it goes through our release process to bump the version appropriately.

**Comment by michael-zhou-lw** [comment]
This change has been released in https://github.com/lacework/helm-charts/pull/156.

**Comment by ajardan** [comment]
Thanks a lot @michael-zhou-lw for your help. Should I just close the PR then ?

**Pull request closed without merging**
